"""
pip1
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print ("Hi")

@aql.dataframe(task_id="python_2")
def python_2_func():
    print("Bye")

default_args={
    "owner": "Abdul Alkhatib,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-01-13", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Abdul Alkhatib": "mailto:abdull.alkhatib@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm5v2blvx078q01lhsgb9n5tj/cloud-ide/cm5v2lmtm0xgk01lmnl7herid/cm5v2ltil07ab01lhi68cnpsc",
    },
)
def pip1():
    python_1 = python_1_func()

    python_2 = python_2_func()

dag_obj = pip1()
